[[block]]
block = "cpu"

[[block]]
block = "temperature"
collapsed = false
format = "{average} avg, {max} max"

[[block]]
block = "memory"
format_mem = "{Mup}%"

[[block]]
block = "disk_space"

[[block]]
block = "networkmanager"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
