[[block]]
block = "cpu"

[[block]]
block = "temperature"
collapsed = false
format = "Avg {average}°C, Max {max}°C"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"

[[block]]
block = "disk_space"

[[block]]
block = "networkmanager"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
